### ISSUE TITLE
Research for open-source RTL for I3c or I2c

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#4]

**Comment by muneebullashariff** [comment]
We can use this I2C RTL to connect with our I3C VIP to demonstrate the backward compatibility.

https://github.com/muneebullashariff/pulpino_soc_uvm_testbench/tree/master/i2c

**Comment by muneebullashariff** [comment]
Read the sections 5.4 for I2C information:



[Pulpinoproject_I2C_datasheet.pdf](https://github.com/mbits-mirafra/i3c_avip/files/13318944/datasheet.2.pdf)

**Comment by muneebullashariff** [comment]
Come up with feature that are supported by this RTL and figure out few area, where a bug could be found

**Comment by muneebullashariff** [comment]
In the RTL, there is TX Register which is of 8bits, thus using this we can send the 7bit address  + R/W access value from the i2c master RTL. Similar thing we can do for sending the data after sending the command.



![Image](https://github.com/mbits-mirafra/i3c_avip/assets/15922511/fe19ca9e-31f9-4ae3-8633-a206716c2f7c)



![Image](https://github.com/mbits-mirafra/i3c_avip/assets/15922511/da934b81-2124-410e-a2bd-9caecfae6d71)

**Comment by mahadevaswamy05** [comment]
We are using the I2C RTL for i3c backward compatible.
 
- Here is the link for the I2C RTL
https://github.com/mbits-mirafra/pulpino__i2c_master__ip_verification/tree/main/src/rtl/i2c_master
