### ISSUE TITLE
Read the existing documents

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#6]
Provide your feedback for each document

- vplan
- assertion plan 
- coverage plan
- architectural document 
- naming conventions

**Comment by muneebullashariff** [comment]
**vplan**
The plan needs to be modified as per the discussed points to include I2c and I3c features

**assertion plan**
Will get updated based on the vpaln

**coverage plan**
This needs to be updated based on the new requirements

**architectural document**
Till chapter 3 it's okay, then we need to modify all because it's a copy paste fro APB project

**naming conventions**
Looks good for now

**Comment by mahadevaswamy05** [comment]
we read the all documents and updated the related things inside the DOC directory folder.

Follow the below link for the latest docs for the v-plan, coverage- plan, and naming convention file.

Verification plan -https://github.com/mbits-mirafra/i3c_avip/blob/production/doc/i3c_avip_main_architectural_document.md 
Coverage plan - https://github.com/mbits-mirafra/i3c_avip/blob/production/doc/i3c_avip_coverage_plan.md
naming conventions plan - https://github.com/mbits-mirafra/i3c_avip/blob/production/doc/i3c_avip_naming_convention.md
