### ISSUE TITLE
Come up with the features that are existing

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#7]
We need to understand the features that are currently implemented in the VIP.

**Comment by mahadevaswamy05** [comment]
## Hot join request 🟠

- The i3c bus protocol supports a mechanism for targets to join the i3c bus after the bus has already been configured this mechanism is called hot join.
-   **The Hot-Join feature** in I3C allows a Master to assign a dynamic address to Another slave when the slave requests it. 
- The hot-join mechanism is used when a target is mounted on the same **I3C** bus and remains depowered until needed. The target can then send a Hot-Join Request when it is powered up.
- The target must wait for the **bus idle condition** before sending the hot join request.
- The bus idle condition is defined as a period during which the bus available status is maintained for a duration of at least t idle that is 200 micros seconds. meaning that the SCL and SDA lines are both held high for the t idle.
- Once the joining target has been assigned its new dynamic address is fully operational on the i3c bus.
- Just follow the thought below picture for more clarity. 




![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/cd5dc6b9-c6bf-4c38-a4eb-a79c7c5de613)

![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/1b233063-bec9-4719-a8e8-d2117dd54d0f)

![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/638f36ef-c6c6-4b56-bf01-8e9eb1e433df)


![image](https://github.com/mbits-mirafra/i3c_avip/assets/106074838/280ec4fa-e7ab-4764-8219-936896117966)

**Comment by Gopalsuthar2308** [comment]
1. Dynamic Address Assignment
2. Hot-Join request support
3. In-Band interrupt support.
4. All Common Command Codes (CCC)

**Comment by muneebullashariff** [comment]
What features have been implemented in the code related to I2c protocol

**Comment by muneebullashariff** [comment]
Run the test - waveform
Which is sequence executed 
What is the sequence doing 
The check what the driver is doing 
Check the waveform

Make the conclusions as to what feature(s) were implemented in this flow.

**write_test**
Test case name : **i3c_8b_write_test**
In the write_sequence file 
Slave_Addrees:- 'b110_1000
write_operation= 0
size = 1 means 1 byte.
randomization data proving to the data line.
and 
reset is active on the negedge clk,
and deactivated on posedge clk.

idle state = 0.

In the waveform, the first LSB bit 0 is receiving which means we are receiving: 000_1011
Working well, the actual writing is happening. 

---


**Read test:-**
Test case name: **i3c_8b_read_test**
Slave_Addrees:- 'b110_1000
Read_operation= 1;
size = 1 means 1 byte.

We are sending an address 110_1000 and receiving the 0001_011 like the LSB bit is first.
And it's 7th bit is 1 and It kind of reads operation that's why the 7th bit is 1. In the waveform.

It works well,

----

**For the CCC test case**

Test case name: i3c_direct_ccc_setdasa_test,
In the virtual sequence, we are pointing to the 8bit_master_write_seq and 8b_slave_seq.

In the 8b_master_write_seq
we are sending the address is 7'b110_1000; 
WRITE = 0;
size =1; 1 byte 8 bits




Coming to the slave_seq
inside the task, we are writing start_item doing the randomization, and printing  the value
Doing the randomization for Slave_address , size , wr_data and rd_data, NO_of_slaves  and raddr;


Here we are sending the MSB = 0 so it's a broadcast message Broadcast means one too many msg it will be sent.
In the waveform, we can able to view the same address after the first address is received and the second slave is receiving the correct address. 

---

for **8b_write_followed_by_read**
Test case name: 8b_write_followed_by_read

In the virtual sequence, we are pointing to the 8bit_master_write_seq and 8b_slave_seq.
it's pointing to the write_followed_by_read_seq; - i3c_master_8b_write_read_seq and i3c_8b_slave_seq 
In the write_followed_by_read_seq : -
slave_address = 7'b110_1000; 
WRITE=0;
SIZE =1 ;
$random data.

and again we are sending 
Slave_address =  7'b110_1000;
READ=1; //Read operation 
SIZE = 1;

In the log file, it received the data but in the simulation itself, it got struck.

**Comment by mahadevaswamy05** [comment]
**Top 5 features to implement, which are unique for I3C**
1. Dynamic address
2. CCC commands - contain an 8-bit CCC ID describing the command that is executed. The MSB of this ID specifies whether this is a broadcast command (bit7 = 0) or a unicast one (bit7 = 1).
3.
4.
5.

**Comment by muneebullashariff** [comment]
**Features that are existing:**
1. Write operation 
2. Read operation - test is getting stuck
3. Acknowledgement basic implementation 

Looks like the work needs to be done again
