### ISSUE TITLE
Plan for what features we will implement

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#8]

**Comment by mahadevaswamy05** [comment]
## Hot join request 🟠

**Comment by muneebullashariff** [comment]
Mahadev
1. Repeated start method:- trying the start followed by stop again start method and followed by stop method.
2. Reset feature: - whenever it required 
3. Dynamic address:- Doing the randomization to locate the slave address.
4. Broadcast feature

**Comment by muneebullashariff** [comment]
The features are decided and the vplan is constructed:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTvY0ET6eZrtU-8REOpf4kg28bNutPH8JKwNUbaU4iYg60xx1LUudmLOoagY6BbEtbaZUOWahtXQkct/pubhtml?gid=0&single=true

**Comment by mahadevaswamy05** [comment]
Follow the v-plan for the features we implemented

https://docs.google.com/spreadsheets/d/1X_vYYdUh4IvAByYXqCB6gL-vQD0tD2mti0r9Jwj54OQ/edit#gid=0
