### ISSUE TITLE
Understand multiple drivers logic in I3C

### ISSUE THREAD

**Issue by muneebullashariff** [mbits-mirafra/i3c_avip#9]
Go through the below video to understand more about signal strengths:

https://youtu.be/zzIM-i6OIk4?si=JrACeWGxCNoifjhh&t=2630

Time stamp: 43:50

**Comment by mahadevaswamy05** [comment]
We followed the YouTube video in there we got like - 
what I'm driving and what I'm sampling, Both are different, then multiple driver concepts will come into the picture.
